spring:
  main:
    banner-mode: "off"
app:
  filename:
    base: src\main\resources\
    source: source.txt
    encrypted: encrypted.txt
    decrypted: decrypted.txt
  cryptography:
    dumb-encryption: 0
    alphabet-numeration-start: 2